// <auto-generated />
using System;
using EcoStepBackend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoStepBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403181923_ContextUpdate")]
    partial class ContextUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("EcoStepBackend.FoodData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MeatEatenOz")
                        .HasColumnType("REAL");

                    b.Property<double>("PlantEatenOz")
                        .HasColumnType("REAL");

                    b.Property<int>("SurveyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("FoodData");
                });

            modelBuilder.Entity("EcoStepBackend.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeatingType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Household");
                });

            modelBuilder.Entity("EcoStepBackend.ResourceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ElectricityConsumptionKWtH")
                        .HasColumnType("REAL");

                    b.Property<int>("SurveyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WaterConsumptionL")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("ResourceData");
                });

            modelBuilder.Entity("EcoStepBackend.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReportedDays")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("EcoStepBackend.TransportData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AirplaneDistanceMiles")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesDiesel")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesElectric")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesHybrid")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesHydrogen")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesMethane")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesPetrol")
                        .HasColumnType("REAL");

                    b.Property<double>("CarDistanceMilesPropane")
                        .HasColumnType("REAL");

                    b.Property<double>("PublicTransportDistanceMiles")
                        .HasColumnType("REAL");

                    b.Property<int>("SurveyId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TrainDistanceMiles")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("TransportData");
                });

            modelBuilder.Entity("EcoStepBackend.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirplaneCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarDieselCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarElectricCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarHybridCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarHydrogenCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarMethaneCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarPetrolCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarPropaneCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectricityCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodMeatCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodPlantCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodWasteCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassRecycledCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlassWasteCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetalRecycledCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetalWasteCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OtherWasteCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperRecycledCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaperWasteCondition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlasticRecycledCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlasticWasteCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicTransportCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainCondition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaterCondition")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("EcoStepBackend.WasteData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("FoodWasteOz")
                        .HasColumnType("REAL");

                    b.Property<double>("GlassRecycledPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("GlassWasteOz")
                        .HasColumnType("REAL");

                    b.Property<double>("MetalRecycledPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("MetalWasteOz")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherWasteOz")
                        .HasColumnType("REAL");

                    b.Property<double>("PaperRecycledPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("PaperWasteOz")
                        .HasColumnType("REAL");

                    b.Property<double>("PlasticRecycledPercent")
                        .HasColumnType("REAL");

                    b.Property<double>("PlasticWasteOz")
                        .HasColumnType("REAL");

                    b.Property<int>("SurveyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId")
                        .IsUnique();

                    b.ToTable("WasteData");
                });

            modelBuilder.Entity("EcoStepBackend.FoodData", b =>
                {
                    b.HasOne("EcoStepBackend.Survey", null)
                        .WithOne("FoodData")
                        .HasForeignKey("EcoStepBackend.FoodData", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.Household", b =>
                {
                    b.HasOne("EcoStepBackend.User", null)
                        .WithOne("Household")
                        .HasForeignKey("EcoStepBackend.Household", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.ResourceData", b =>
                {
                    b.HasOne("EcoStepBackend.Survey", null)
                        .WithOne("ResourceData")
                        .HasForeignKey("EcoStepBackend.ResourceData", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.Survey", b =>
                {
                    b.HasOne("EcoStepBackend.User", null)
                        .WithMany("Surveys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.TransportData", b =>
                {
                    b.HasOne("EcoStepBackend.Survey", null)
                        .WithOne("TransportData")
                        .HasForeignKey("EcoStepBackend.TransportData", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.WasteData", b =>
                {
                    b.HasOne("EcoStepBackend.Survey", null)
                        .WithOne("WasteData")
                        .HasForeignKey("EcoStepBackend.WasteData", "SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.Survey", b =>
                {
                    b.Navigation("FoodData")
                        .IsRequired();

                    b.Navigation("ResourceData")
                        .IsRequired();

                    b.Navigation("TransportData")
                        .IsRequired();

                    b.Navigation("WasteData")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoStepBackend.User", b =>
                {
                    b.Navigation("Household");

                    b.Navigation("Surveys");
                });
#pragma warning restore 612, 618
        }
    }
}
